title: Zack Strathe # page title
tagline: Data Scientist &#124; Portfolio
description: A portfolio of data science projects for Zack Strathe
social:
  name: Zack Strathe
  links:
    - https://www.linkedin.com/in/zack-strathe
    - https://github.com/zstrathe

#logo: "/images/profile.jpg?raw=true" your photo (or logo) here 
my-info: >  # your text below (remove <br> elements if you don't need line breaks)
  <b>M.S. Data Analytics at Kansas State University
  <br>
  &bull; Data Science Track
  <br>
  &bull; Completion Date: August 2022
  </b>
  <br><br>
  <a href="/pdf/ZackStratheResume.pdf"><b>Résumé</b></a>
  <br>
  <p align="left">
     <a href="https://www.credly.com/badges/b5ea736f-bafb-4748-953c-604852744399"> <img src="/images/cert.png"></a>
  </p>
  <a href="https://www.linkedin.com/in/zack-strathe">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-228764558-1  # your Google Analytics tracking ID here
