title: Zack Strathe # page title
logo: "/images/profile.jpg?raw=true" 
tagline: Portfolio &#124; Data Science
description: data science project portfolio
social:
  name: Zack Strathe
  links:
    - https://www.linkedin.com/in/zack-strathe
    - https://github.com/zstrathe

#logo: "/images/profile.jpg?raw=true" your photo (or logo) here 
my-info: >  # your text below (remove <br> elements if you don't need line breaks)
  <b>M.S. Data Analytics</b> at Kansas State University
  <br>
  &bull; Data Science Program Track
  <br>
  &bull; Graduated August 2022
  <br><br>
  <a href="/pdf/ZackStratheResume.pdf"><b>Résumé</b></a>
  <p align="left">
     <a href="https://www.credly.com/badges/b5ea736f-bafb-4748-953c-604852744399"> <img src="/images/cert.png"></a>
  </p>
  <a href="https://www.linkedin.com/in/zack-strathe">View My LinkedIn Profile</a><br><br>
  <a href="https://github.com/zstrathe">View My Github Profile</a><br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-228764558-1  # your Google Analytics tracking ID here
