title: Zack Strathe # your name (or website title) here
logo: "" # your photo (or logo) here /images/profile.jpg?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>M.S. Data Analytics at Kansas State University
  <br>
  - Data Science Track
  <br>
  - Completion: August 2022
  </b>
  <br><br>
  <a href="/pdf/ZackStratheResume.pdf"><b>Résumé</b></a>
  <br>
  <p align="center">
     <a href="https://www.credly.com/badges/b5ea736f-bafb-4748-953c-604852744399"> <img src="/images/cert.png"></a>
  </p>
  <br>
  <a href="https://www.linkedin.com/in/zack-strathe">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-228764558-1  # your Google Analytics tracking ID here
